ALTER TABLE roster_book
  ADD COLUMN IF NOT EXISTS class_name  VARCHAR(100) DEFAULT '',
  ADD COLUMN IF NOT EXISTS reg_boys    INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS reg_girls   INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pres_boys   INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pres_girls  INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS abs_boys    INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS abs_girls   INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS perm_boys   INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS perm_girls  INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sick_boys   INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sick_girls  INT DEFAULT 0;